# Site settings
title: Bocong Zheng
email: bzheng@fraunhofer.org
description: Academic webpage of Bocong Zheng
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
google_analytics: UA-187518795-1

# Footer info
# affiliation: >
#     Bocong Zheng<br/>
#     Scientist<br/>
#     <a href="https://www.ccd.fraunhofer.org/" target="_blank">Center Midwest</a><br/>
#     Fraunhofer USA

# location: >
#   Fraunhofer USA Center Midwest<br/>
#   Michigan State University<br/>
#   1449 Engineering Research Ct.<br/>
#   East Lansing, MI 48824

contact: >
    <a href="mailto:bcong.zheng@gmail.com" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Bocong via email</a> <br/>
#   <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  # - name: about
  - name: publications
  - name: talks
  - name: research
  # - name: software
# - name: team
# - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - switch_theme.sh
  - makebib.py
